TAXI-08 Data cleaner
dk1000/hubquest_taxi pull request #11
Opened 2023-11-01 10:31 UTC by AdamJedz

Data cleaner class created and incorporated into make_dataset pipeline

2023-11-01 10:33 UTC, AdamJedz commented
I need to ask you guys - do we want to remove outliers (bad data) from the columns that we don't use (we don't know - like trip distance or trip time)?

2023-11-03 15:05 UTC, dk1000 requested changes
There are conflicts for commited changes. Moreover, please make sure imports are in right order, you can use 'isort .' in terminal. 

Cleaning fine.

2023-11-06 08:53 UTC, AdamJedz commented
@dk1000 I ran isort, but could you be more specific what "right order" means regarding imports?

2023-11-06 09:13 UTC, dk1000 approved these changes

2023-11-06 09:15 UTC, merged