TAXI-06 train test split
dk1000/hubquest_taxi pull request #7
Opened 2023-10-30 08:21 UTC by AdamJedz

train test split (date wise) in a function that can be used in the main/train_model script

2023-10-30 09:13 UTC, dk1000 requested changes
A general comment about code formatting, I see no formatting applied. I use black to obey PEP8 rules and works quite perfect

2023-10-30 09:13 UTC, dk1000 commented on src/data/data_split.py
> +    df = pd.read_parquet(data_path + 'final_taxi_data.parquet').sort_values('pickup_datetime').reset_index(drop=True)
I would definitely put file name (final_data etc) as an argument, so we can run main.py with config file containing code-specific info and keep code clean with the least amount of dependencies. To be discussed as always

2023-10-30 15:17 UTC, AdamJedz commented
Please check now. You can test it either by running make_dataset.py or main.py. There is one #TODO - to run it with parameters read from config.yml, but we'll resolve it later

2023-10-31 10:00 UTC, dk1000 approved these changes

2023-10-31 10:04 UTC, merged